const team = [
  {
    value: "Faculty In-Charges",
    title: "Faculty In-Charges",
    members: [
      {
        name: "Dr. Shalu Chopra",
        email: "shalu.chopra@ves.ac.in",
        designation: "Head of Department",
        linkedin: "https://in.linkedin.com/in/dr-shalu-chopra-45aa0bb4",
        image:
          "https://res.cloudinary.com/bytewise0405/image/upload/v1738410344/QuestIT/Team/Faculty%20Advisors/shalu-chopra_jyyyz8.jpg",
      },
      {
        name: "Dr. Manoj Sabnis",
        designation: "Deputy HOD",
        email: "manoj.sabnis@ves.ac.in",
        linkedin: "https://in.linkedin.com/in/manoj-sabnis-36560146",
        image:
          "https://res.cloudinary.com/bytewise0405/image/upload/v1738410344/QuestIT/Team/Faculty%20Advisors/manoj-sabnis_yncyqs.jpg",
      },
      {
        name: "Kajal Jewani",
        designation: "Faculty In-Charge",
        email: "kajal.jewani@ves.ac.in",
        linkedin: "https://www.linkedin.com/in/joseph-kajal-bb761a2b",
        image:
          "https://res.cloudinary.com/bytewise0405/image/upload/v1738410344/QuestIT/Team/Faculty%20Advisors/kajal-jewani_lbaeml.jpg",
      },
      {
        name: "Charusheela Nehete",
        designation: "Faculty In-Charge",
        email: "charusheela.nehete@ves.ac.in",
        linkedin: "https://in.linkedin.com/in/charusheela-nehete-65436035",
        image:
          "https://res.cloudinary.com/bytewise0405/image/upload/v1738410345/QuestIT/Team/Faculty%20Advisors/charusheela-nehete_hli5id.jpg",
      },
    ],
  },
  {
    value: "Quest IT Council 2026-27",
    title: "Quest IT Council 2026-27",
    subGroups: [
      {
        value: "BE Members",
        title: "BE Members",
        members: [
          {
            name: "Archit Chitte",
            designation: "Graphics Head",
            email: "2023.archit.chitte@ves.ac.in",
            github: "https://github.com/architchitte",
            linkedin: "https://in.linkedin.com/in/archit-chitte-4551ba288",
            image: "/images/team2026/beMembers/ArchitChitte.jpg",
          },
          {
            name: "Atharva Lotankar",
            designation: "Technical Head",
            email: "2023.atharva.lotankar@ves.ac.in",
            github: "https://www.github.com/AtharvaLotankar11",
            linkedin: "http://www.linkedin.com/in/atharva-lotankar-51824537b",
            image: "/images/team2026/beMembers/AtharvaLotankar.jpg",
          },
          {
            name: "Atharva Pingale",
            designation: "Content Head",
            email: "2023.atharva.pingale@ves.ac.in",
            github: "https://github.com/Atharvasp333",
            linkedin: "https://www.linkedin.com/in/atharva-pingale-25387432a/",
            image: "/images/team2026/beMembers/AtharvaPingale.jpg",
          },
          {
            name: "Nupur Ghangarekar",
            designation: "Public Relations Head",
            email: "2023.nupur.ghangarekar@ves.ac.in",
            github: "https://github.com/NupurGhangarekar",
            linkedin: "https://www.linkedin.com/in/nupur-ghangarekar/",
            image: "/images/team2026/beMembers/NupurGhangarekar.jpg",
          },
          {
            name: "Shravanya Andhale",
            designation: "Technical Head",
            email: "2023.shravanya.andhale@ves.ac.in",
            github: "https://github.com/Shravanya178",
            linkedin: "https://www.linkedin.com/in/shravanya-andhale-b729a2314/",
            image: "/images/team2026/beMembers/ShravanyaAndhale.jpg",
          },
          {
            name: "Tanaya Jain",
            designation: "Secretary",
            email: "2023.tanaya.jain@ves.ac.in",
            github: "https://github.com/tanaya2005",
            linkedin: "https://www.linkedin.com/in/jaintanaya",
            image: "/images/team2026/beMembers/TanayaJain.jpg",
          },
          {
            name: "Varun Rahatgaonkar",
            designation: "Secretary",
            email: "2023.varun.rahatgaonkar@ves.ac.in",
            github: "https://github.com/Kingslaye-varun",
            linkedin: "http://www.linkedin.com/in/varun-rahatgaonkar-448392321",
            image: "/images/team2026/beMembers/VarunRahatgaonkar.jpg",
          },
        ],
      },
      {
        value: "TE Members",
        title: "TE Members",
        members: [
          {
            name: "Ankita Punjabi",
            designation: "SR Treasurer",
            email: "2024.ankita.punjabi@ves.ac.in",
            github: "https://github.com/ankitapunjabi22",
            linkedin: "https://www.linkedin.com/in/ankita-punjabi-4b80aa375",
            image: "/images/team2026/teMembers/AnkitaPunjabi.jpg",
          },
          {
            name: "Aryan Kadam",
            designation: "SR Public Relations Officer",
            email: "2024.aryan.kadam@ves.ac.in",
            github: "https://github.com/Aryert05",
            linkedin: "https://www.linkedin.com/in/aryan-kadam-546315325/",
            image: "/images/team2026/teMembers/AryanKadam.jpg",
          },
          {
            name: "Ashutosh Mishra",
            designation: "SR Technical Officer",
            email: "2024.ashutosh.mishra@ves.ac.in",
            github: "https://github.com/Dev-Am12",
            linkedin: "https://www.linkedin.com/in/ashutosh-mishra12/",
            image: "/images/team2026/teMembers/AshutoshMishra.jpg",
          },
          {
            name: "Atharva Waghmode",
            designation: "SR Graphics Officer",
            email: "2024.atharva.waghmode@ves.ac.in",
            github: "https://github.com/wagha-builds",
            linkedin: "https://www.linkedin.com/in/atharva-waghmode-0a7573350",
            image: "/images/team2026/teMembers/AtharvaWaghmode.jpg",
          },
          {
            name: "Ayush Lokhande",
            designation: "SR Public Relations Officer",
            email: "2024.ayush.lokhande@ves.ac.in",
            github: "https://github.com/Ayushpro45",
            linkedin: "https://www.linkedin.com/in/ayush-lokhande-33306433b/",
            image: "/images/team2026/teMembers/AyushLokhande.jpg",
          },
          {
            name: "Japleen Kaur Arora",
            designation: "Deputy Seceratary",
            email: "2024.japleen.arora@ves.ac.in",
            github: "https://github.com/japleenkaurarora17",
            linkedin: "https://www.linkedin.com/in/japleen-kaur-arora-a805aa312",
            image: "/images/team2026/teMembers/JapleenKaurArora.jpg",
          },
          {
            name: "Kirteesh Rakshe",
            designation: "SR Graphics Officer",
            email: "2024.kirteesh.rakshe@ves.ac.in",
            github: "https://github.com/kirteexh",
            linkedin: "https://www.linkedin.com/in/kirteesh-r-87617139b",
            image: "/images/team2026/teMembers/KirteeshRakshe.jpg",
          },
          {
            name: "Krishna Gavali",
            designation: "SR Treasurer",
            email: "2024.krishna.gavali@ves.ac.in",
            github: "https://github.com/krishnagavali20",
            linkedin: "https://www.linkedin.com/in/krishna-gavali-962a233a8",
            image: "/images/team2026/teMembers/KrishnaGavali.jpg",
          },
          {
            name: "Naina Bajaj",
            designation: "SR Public Relations Officer",
            email: "2024.naina.bajaj@ves.ac.in",
            github: "https://github.com/nainabajaj27",
            linkedin: "https://www.linkedin.com/in/naina-bajaj-a89134405",
            image: "/images/team2026/teMembers/NainaBajaj.jpg",
          },
          {
            name: "Om Sawlani",
            designation: "SR Graphics Officer",
            email: "2024.om.sawlani@ves.ac.in",
            github: "https://github.com/Om23102006",
            linkedin: "https://www.linkedin.com/in/om-sawlani-4b11a2398",
            image: "/images/team2026/teMembers/OmSawlani.jpg",
          },
          {
            name: "Parth Chavan",
            designation: "SR Public Relations Officer",
            email: "2024.parth.chavan@ves.ac.in",
            github: "https://github.com/Parth-Chavan-15",
            linkedin: "https://www.linkedin.com/in/parth-chavan-8b9260394",
            image: "/images/team2026/teMembers/ParthChavan.jpg",
          },
          {
            name: "Pavan Wadhwa",
            designation: "SR Content Officer",
            email: "2024.pavan.wadhwa@ves.ac.in",
            github: "https://github.com/pavanwadhwa2006-ai",
            linkedin: "https://www.linkedin.com/in/pavan-wadhwa-323537290",
            image: "/images/team2026/teMembers/PavanWadhwa.jpg",
          },
          {
            name: "Pradnyesh Patil",
            designation: "Deputy Seceratary",
            email: "2024.pradnyesh.patil@ves.ac.in",
            github: "https://github.com/pradsgoat7",
            linkedin: "https://www.linkedin.com/in/pradnyesh-patil-aba90a221/",
            image: "/images/team2026/teMembers/PradnyeshPatil.jpg",
          },
          {
            name: "Rushabh Gupta",
            designation: "SR Technical Officer",
            email: "2024.rushabh.gupta@ves.ac.in",
            github: "https://github.com/RiShBhs-Code",
            linkedin: "https://www.linkedin.com/in/rushabh-gupta-8b0119381",
            image: "/images/team2026/teMembers/RushabhGupta.jpg",
          },
          {
            name: "Sanjog Poojary",
            designation: "SR Technical Officer",
            email: "2024.sanjog.poojary@ves.ac.in",
            github: "https://github.com/Sanjog-Poojary",
            linkedin: "https://www.linkedin.com/in/sanjog-poojary-08871032a",
            image: "/images/team2026/teMembers/SanjogPoojary.jpg",
          },
          {
            name: "Shivam Mishra",
            designation: "SR Technical Officer",
            email: "2024.shivam.mishra@ves.ac.in",
            github: "https://github.com/thetwobraincells",
            linkedin: "https://www.linkedin.com/in/shivamrpmishra/",
            image: "/images/team2026/teMembers/ShivamMishra.jpg",
          },
          {
            name: "Soniya Lulla",
            designation: "SR Public Relations Officer",
            email: "2024.soniya.lulla@ves.ac.in",
            github: "https://github.com/SoniyaDev",
            linkedin: "https://www.linkedin.com/in/soniya-lulla-36b072338",
            image: "/images/team2026/teMembers/SoniyaLulla.jpg",
          },
          {
            name: "Tanaya Pawar",
            designation: "SR Graphics Officer",
            email: "2024.tanaya.pawar@ves.ac.in",
            github: "https://github.com/Tangerinn",
            linkedin: "https://in.linkedin.com/in/tanaya-pawar-7420aa379",
            image: "/images/team2026/teMembers/TanayaPawar.jpg",
          },
        ],
      },
      {
        value: "SE Members",
        title: "SE Members",
        members: [
          {
            name: "Adit Kondlekar",
            designation: "JR Public Relations Officer",
            email: "2025.adit.kondlekar@ves.ac.in",
            github: "https://github.com/Adit-starter",
            linkedin: "https://www.linkedin.com/in/adit-kondlekar-380734437",
            image: "/images/team2026/seMembers/AditKondlekar.jpg",
          },
          {
            name: "Antara Dhavan",
            designation: "JR Graphics Officer",
            email: "2025.antara.dhavan@ves.ac.in",
            github: "https://github.com/antara837",
            linkedin: "https://www.linkedin.com/in/antara-dhavan-04187a3ab",
            image: "/images/team2026/seMembers/AntaraDhavan.jpg",
          },
          {
            name: "Anushka Chaurarsia",
            designation: "JR Content Officer",
            email: "2025.anushka.chaurasia@ves.ac.in",
            github: "https://github.com/anushkachaurasia087-stack",
            linkedin: "https://www.linkedin.com/in/anushka-chaurasia-916801408",
            image: "/images/team2026/seMembers/AnushkaChaurasia.jpg",
          },
          {
            name: "Arvesh Kumbhare",
            designation: "JR Public Relations Officer",
            email: "2025.arvesh.kumbhare@ves.ac.in",
            github: "https://github.com/Arveshk",
            linkedin: "https://www.linkedin.com/in/arveshkumbhare/",
            image: "/images/team2026/seMembers/ArveshKumbhare.jpg",
          },
          {
            name: "Avani Killekar",
            designation: "JR Techinical Officer",
            email: "2025.avani.killekar@ves.ac.in",
            github: "https://github.com/avanikillekar",
            linkedin: "https://www.linkedin.com/in/avani-killekar-4184573b8",
            image: "/images/team2026/seMembers/AvaniKillekar.jpg",
          },
          {
            name: "Ayush Gaikwad",
            designation: "JR Graphics Officer",
            email: "2025.ayush.gaikwad@ves.ac.in",
            github: "https://github.com/AyushG-789",
            linkedin: "https://www.linkedin.com/in/ayush-gaikwad-b01083386",
            image: "/images/team2026/seMembers/AyushGaikwad.jpg",
          },
          {
            name: "Chaitali Rane",
            designation: "JR Techinical Officer",
            email: "2025.chaitali.rane@ves.ac.in",
            github: "https://github.com/C172007",
            linkedin: "https://www.linkedin.com/in/chaitalirane1707",
            image: "/images/team2026/seMembers/ChaitaliRane.jpg",
          },
          {
            name: "Hardik Verma",
            designation: "JR Treasurer",
            email: "2025.hardik.verma@ves.ac.in",
            github: "https://github.com/xHardik",
            linkedin: "https://www.linkedin.com/in/hardik-verma-6387ab25a",
            image: "/images/team2026/seMembers/HardikVerma.jpg",
          },
          {
            name: "Kanishka Lulla",
            designation: "JR Content Officer",
            email: "2025.kanishka.lulla@ves.ac.in",
            github: "https://github.com/kanishkalulla",
            linkedin: "https://www.linkedin.com/in/kanishka-lulla-843364373",
            image: "/images/team2026/seMembers/KanishkaLulla.jpg",
          },
          {
            name: "Karmanya Jakhotia",
            designation: "JR Public Relations Officer",
            email: "2025.karmanya.jakhotia@ves.ac.in",
            github: "https://github.com/Karmanya-Jakhotia",
            linkedin: "https://www.linkedin.com/in/karmanya-jakhotia-9b1420385",
            image: "/images/team2026/seMembers/KarmanyaJakhotia.jpg",
          },
          {
            name: "Karthik Kotian",
            designation: "JR Techinical Officer",
            email: "2025.karthik.kotian@ves.ac.in",
            github: "https://github.com/codecruncher0723",
            linkedin: "https://www.linkedin.com/in/karthik-kotian-3aa590384",
            image: "/images/team2026/seMembers/KarthikKotian.jpg",
          },
          {
            name: "Manasvi Wairkar",
            designation: "JR Treasurer",
            email: "2025.manasvi.wairkar@ves.ac.in",
            github: "https://github.com/manasviwairkar",
            linkedin: "https://www.linkedin.com/in/manasvi-wairkar-00724a368",
            image: "/images/team2026/seMembers/ManasviWairkar.jpg",
          },
          {
            name: "Manish Awari",
            designation: "JR Techinical Officer",
            email: "2025.manish.awari@ves.ac.in",
            github: "https://github.com/themanishawari",
            linkedin: "https://www.linkedin.com/in/manishawari/",
            image: "/images/team2026/seMembers/ManishAwari.jpg",
          },
          {
            name: "Rajwardhan Patil",
            designation: "JR Public Relations Officer",
            email: "2025.rajwardhan.patil@ves.ac.in",
            github: "https://github.com/Rajwardhan-09",
            linkedin: "https://www.linkedin.com/in/rajwardhan-patil-829992362",
            image: "/images/team2026/seMembers/RajwardhanPatil.jpg",
          },
          {
            name: "Sachin Kumawat",
            designation: "JR Graphics Officer",
            email: "2025.sachin.kumawat@ves.ac.in",
            github: "https://github.com/CooLHecker",
            linkedin: "https://www.linkedin.com/in/sachin-kumawat-181148363",
            image: "/images/team2026/seMembers/SachinKumawat.jpg",
          },
          {
            name: "Sakshi Shetty",
            designation: "JR Graphics Officer",
            email: "2025.sakshi.shetty@ves.ac.in",
            github: "https://github.com/S-2107",
            linkedin: "https://www.linkedin.com/in/sakshi-shetty-028728440",
            image: "/images/team2026/seMembers/SakshiShetty.jpg",
          },
          {
            name: "Sanchita Patil",
            designation: "JR Public Relations Officer",
            email: "2025.sanchita.patil@ves.ac.in",
            github: "https://github.com/sanchitapatil02",
            linkedin: "https://www.linkedin.com/in/sanchita-patil-59149026b",
            image: "/images/team2026/seMembers/SanchitaPatil.jpg",
          },
          {
            name: "Sankalp Mane",
            designation: "JR Techinical Officer",
            email: "2025.sankalp.mane@ves.ac.in",
            github: "https://github.com/Sankymane",
            linkedin: "https://www.linkedin.com/in/sankalp-mane-53175936b",
            image: "/images/team2026/seMembers/SankalpMane.jpg",
          },
          {
            name: "Sarra Khadse",
            designation: "JR Techinical Officer",
            email: "2025.sarra.khadse@ves.ac.in",
            github: "https://github.com/sarrakhadse07",
            linkedin: "https://www.linkedin.com/in/sarra-khadse-0b7719386",
            image: "/images/team2026/seMembers/SarraKhadse.jpg",
          },
          {
            name: "Snehanshu Deo",
            designation: "JR Content Officer",
            email: "2025.snehansu.deo@ves.ac.in",
            github: "https://github.com/snehanshuuu",
            linkedin: "https://www.linkedin.com/in/snehansu-deo",
            image: "/images/team2026/seMembers/SnehanshuDeo.jpg",
          },
          {
            name: "Sujoy Neogy",
            designation: "JR Graphics Officer",
            email: "2025.neogy.sujoy@ves.ac.in",
            github: "https://github.com/sujoygoestothemoon",
            linkedin: "https://www.linkedin.com/in/sujoy-neogy-726582383",
            image: "/images/team2026/seMembers/SujoyNeogy.jpg",
          },
          {
            name: "Yash Sawant",
            designation: "JR Graphics Officer",
            email: "2025.yash.sawant@ves.ac.in",
            github: "https://github.com/yashsawant-vesit",
            linkedin: "https://www.linkedin.com/in/yash-sawant-711105362/",
            image: "/images/team2026/seMembers/YashSawant.jpg",
          },
        ],
      },
    ],
  },
  {
    value: "Quest IT Council 2025-26",
    title: "Quest IT Council 2025-26",
    subGroups: [
      {
        value: "BE Members",
        title: "BE Members",
        members: [
          {
            name: "Ajinkya Patil",
            designation: "Content Head",
            email: "2022.ajinkya.patil@ves.ac.in",
            github: "https://github.com/ajinkyaspatil20",
            linkedin: "https://www.linkedin.com/in/ajinkyaspatil20",
            image: "/images/team2025/beMembers/AjinkyaPatil.png",
          },
          {
            name: "Eesha Chavan",
            designation: "Secretary",
            email: "2022.eesha.chavan@ves.ac.in",
            github: "https://github.com/eeshachavan",
            linkedin: "https://www.linkedin.com/in/eesha-chavan",
            image: "/images/team2025/beMembers/EeshaChavan.png",
          },
          {
            name: "Krushikesh Shelar",
            designation: "Technical Head",
            email: "2022.krushikesh.shelar@ves.ac.in",
            github: "https://github.com/KrushikeshS",
            linkedin: "https://in.linkedin.com/in/krushikesh-shelar",
            image: "/images/team2025/beMembers/KrushikeshShelar.png",
          },
          {
            name: "Pranav Titambe",
            designation: "Secretary",
            email: "2022.pranav.titambe@ves.ac.in",
            github: "https://github.com/Pranavlovescode",
            linkedin: "https://in.linkedin.com/in/pranav-titambe",
            image: "/images/team2025/beMembers/PranavTitambe.png",
          },
          {
            name: "Ronak Katariya",
            designation: "Public Relations Head",
            email: "2022.ronak.katariya@ves.ac.in",
            github: "https://github.com/ronak03rsk",
            linkedin: "https://www.linkedin.com/in/ronak-katariya-02877b284",
            image: "/images/team2025/beMembers/RonakKatariya.png",
          },
          {
            name: "Sannidhi Kailaje",
            designation: "Graphics Head",
            email: "2022.sannidhi.kailaje@ves.ac.in",
            github: "https://github.com/Skailaje",
            linkedin: "https://www.linkedin.com/in/sannidhi-kailaje-011a312a4",
            image: "/images/team2025/beMembers/SannidhiKailaje.png",
          },
          {
            name: "Shravani Rasam",
            designation: "Technical Head",
            email: "2022.shravani.rasam@ves.ac.in",
            github: "https://github.com/ShravaniR2412",
            linkedin: "https://www.linkedin.com/in/shravanirasam02",
            image: "/images/team2025/beMembers/ShravaniRasam.png",
          },
        ],
      },
      {
        value: "TE Members",
        title: "TE Members",
        members: [
          {
            name: "Anish Tawade",
            designation: "Deputy Secretary",
            email: "2023.anish.tawade@ves.ac.in",
            github: "https://github.com/Anissh280507",
            linkedin: "https://in.linkedin.com/in/anish-tawade-53a82a1ba",
            image: "/images/team2025/teMembers/AnishTawade.png",
          },
          {
            name: "Archit Chitte",
            designation: "SR Graphics Officer",
            email: "2023.archit.chitte@ves.ac.in",
            github: "https://github.com/architchitte",
            linkedin: "https://in.linkedin.com/in/archit-chitte-4551ba288",
            image: "/images/team2025/teMembers/ArchitChitte.png",
          },
          {
            name: "Arnav Chaudhary",
            designation: "SR Technical Officer",
            email: "2023.arnav.chaudhary@ves.ac.in",
            github: "https://github.com/Arnavch2024",
            linkedin: "https://www.linkedin.com/in/arnav-chaudhary-2a526928b",
            image: "/images/team2025/teMembers/ArnavChaudhary.png",
          },
          {
            name: "Atharva Lotankar",
            designation: "SR Technical Officer",
            email: "2023.atharva.lotankar@ves.ac.in",
            github: "https://github.com/AtharvaLotankar11",
            linkedin: "https://www.linkedin.com/in/atharva-lotankar-51824537b",
            image: "/images/team2025/teMembers/AtharvaLotankar.png",
          },
          {
            name: "Atharva Pingale",
            designation: "SR Content Officer",
            email: "2023.atharva.pingale@ves.ac.in",
            github: "https://github.com/Atharvasp333",
            linkedin: "https://www.linkedin.com/in/atharva-pingale-25387432a/",
            image: "/images/team2025/teMembers/AtharvaPingale.png",
          },
          {
            name: "Bhavik Panjapi",
            designation: "SR Public Relations Officer",
            email: "2023.bhavik.panjapi@ves.ac.in",
            github: "https://github.com/BhavikPanjapi",
            linkedin: "https://www.linkedin.com/in/bhavik-panjapi-259b772a6/",
            image: "/images/team2025/teMembers/BhavikPanjapi.png",
          },
          {
            name: "Gargi Dhuri",
            designation: "SR Content Officer",
            email: "2023.gargi.dhuri@ves.ac.in",
            github: "https://github.com/gragznotkool",
            linkedin: "https://www.linkedin.com/in/gargi-dhuri-3992aa316/",
            image: "/images/team2025/teMembers/GargiDhuri.png",
          },
          {
            name: "Harsh Kumar",
            designation: "SR Public Relations Officer",
            email: "2023.harsh.kumar@ves.ac.in",
            github: "https://github.com/harshre786",
            linkedin: "https://www.linkedin.com/in/harsh-kumar-5864c92a7/",
            image: "/images/team2025/teMembers/HarshKumar.png",
          },
          {
            name: "Harshita Singh",
            designation: "SR Technical Officer",
            email: "2023.harshita.singh@ves.ac.in",
            github: "https://github.com/Harshita-Singh-25",
            linkedin: "https://www.linkedin.com/in/harshita-singh-3846302a4",
            image: "/images/team2025/teMembers/HarshitaSingh.png",
          },
          {
            name: "Mohish Padave",
            designation: "SR Graphics Officer",
            email: "2023.mohish.padave@ves.ac.in",
            github: "https://github.com/MohishPadave",
            linkedin: "https://www.linkedin.com/in/mohish-padave/",
            image: "/images/team2025/teMembers/MohishPadave.png",
          },
          {
            name: "Nidhi Puthran",
            designation: "SR Graphics Officer",
            email: "2023.nidhi.puthran@ves.ac.in",
            github: "https://github.com/nidhi0810",
            linkedin: "https://www.linkedin.com/in/nidhi-puthran-2824a9299",
            image: "/images/team2025/teMembers/NidhiPuthran.png",
          },
          {
            name: "Nupur Ghangarekar",
            designation: "SR Public Relations Officer",
            email: "2023.nupur.ghangarekar@ves.ac.in",
            github: "https://github.com/NupurGhangarekar",
            linkedin: "https://www.linkedin.com/in/nupur-ghangarekar-60291b291",
            image: "/images/team2025/teMembers/NupurGhangarekar.png",
          },
          {
            name: "Shravanya Andhale",
            designation: "SR Technical Officer",
            email: "2023.shravanya.andhale@ves.ac.in",
            github: "https://github.com/Shravanya178",
            linkedin: "https://www.linkedin.com/in/shravanya-andhale-b729a2314",
            image: "/images/team2025/teMembers/ShravanyaAndhale.png",
          },
          {
            name: "Tanaya Jain",
            designation: "SR Public Relations Officer",
            email: "2023.tanaya.jain@ves.ac.in",
            github: "https://github.com/tanaya2005",
            linkedin: "https://www.linkedin.com/in/jaintanaya/",
            image: "/images/team2025/teMembers/TanayaJain.png",
          },
          {
            name: "Vaishnavi Avhad",
            designation: "SR Technical Officer",
            email: "2023.vaishnavi.avhad@ves.ac.in",
            github: "https://github.com/Vaishnavii-01",
            linkedin: "https://www.linkedin.com/in/vaishnavi-avhad-056969330",
            image: "/images/team2025/teMembers/VaishnaviAvhad.png",
          },
          {
            name: "Varun Rahatgaonkar",
            designation: "Deputy Secretary",
            email: "2023.varun.rahatgaonkar@ves.ac.in",
            github: "https://github.com/kingslaye-varun",
            linkedin: "https://www.linkedin.com/in/varun-rahatgaonkar-448392321",
            image: "/images/team2025/teMembers/VarunRahatgaonkar.png",
          },
        ],
      },
      {
        value: "SE Members",
        title: "SE Members",
        members: [
          {
            name: "Akshat Korde",
            designation: "JR Technical Officer",
            email: "2024.akshat.korde@ves.ac.in",
            github: "https://github.com/akshat1456",
            linkedin: "https://www.linkedin.com/in/akshat-korde-9b37a737a/",
            image: "/images/team2025/seMembers/AkshatKorde.png",
          },
          {
            name: "Ashutosh Mishra",
            designation: "JR Technical Officer",
            email: "2024.ashutosh.mishra@ves.ac.in",
            github: "https://github.com/Dev-Am12",
            linkedin: "https://www.linkedin.com/in/ashutosh-mishra-836b50367/",
            image: "/images/team2025/seMembers/AshutoshMishra.png",
          },
          {
            name: "Atharva Waghmode",
            designation: "JR Graphics Officer",
            email: "2024.atharva.waghmode@ves.ac.in",
            github: "https://github.com/wagha-builds",
            linkedin: "https://www.linkedin.com/in/atharva-waghmode-0a7573350/",
            image: "/images/team2025/seMembers/AtharvaWaghmode.png",
          },
          {
            name: "Ayush Lokhande",
            designation: "JR Public Relations Officer",
            email: "2024.ayush.lokhande@ves.ac.in",
            github: "https://github.com/Ayushpro45",
            linkedin: "https://www.linkedin.com/in/ayush-lokhande-33306433b/",
            image: "/images/team2025/seMembers/AyushLokhande.png",
          },
          {
            name: "Gourish Naik",
            designation: "JR Graphics Officer",
            email: "2024.gourish.naik@ves.ac.in",
            github: "https://github.com/gourishnaikk",
            linkedin: "https://www.linkedin.com/in/gourish-naik-876171334/",
            image: "/images/team2025/seMembers/GourishNaik.png",
          },
          {
            name: "Japleen Kaur Arora",
            designation: "JR Graphics Officer",
            email: "2024.japleen.arora@ves.ac.in",
            github: "https://github.com/2024japleenarora",
            linkedin: "https://www.linkedin.com/in/japleen-kaur-arora-a805aa312/",
            image: "/images/team2025/seMembers/JapleenKArora.png",
          },
          {
            name: "Kirteesh Rakshe",
            designation: "JR Graphics Officer",
            email: "2024.kirteesh.rakshe@ves.ac.in",
            github: "https://github.com/kirteexh",
            linkedin: "https://www.linkedin.com/in/kirteesh-r-87617139b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
            image: "/images/team2025/seMembers/KirteeshRakshe.png",
          },
          {
            name: "Krrish Gupta",
            designation: "JR Technical Officer",
            email: "2024.krrish.gupta@ves.ac.in",
            github: "https://github.com/Krrish-Gupta-18",
            linkedin: "https://www.linkedin.com/in/krrish-gupta-2b7255358/",
            image: "/images/team2025/seMembers/KrrishGupta.png",
          },
          {
            name: "Parth Chavan",
            designation: "JR Public Relations Officer",
            email: "2024.parth.chavan@ves.ac.in",
            github: "https://github.com/Parth-Chavan-15",
            linkedin: "https://www.linkedin.com/in/parth-chavan-8b9260394/",
            image: "/images/team2025/seMembers/ParthChavan.png",
          },
          {
            name: "Parth Khismatrao",
            designation: "JR Public Relations Officer",
            email: "2024.parth.khismatrao@ves.ac.in",
            github: "https://github.com/smokycoder22",
            linkedin: "https://www.linkedin.com/in/parth-khismatrao-77668b36a/",
            image: "/images/team2025/seMembers/ParthKhismatrao.png",
          },
          {
            name: "Rushabh Gupta",
            designation: "JR Technical Officer",
            email: "2024.rushabh.gupta@ves.ac.in",
            github: "https://github.com/RiShBhs-Code",
            linkedin: "https://www.linkedin.com/in/rushabh-gupta-8b0119381/",
            image: "/images/team2025/seMembers/RushabhGupta.png",
          },
          {
            name: "Shivam Mishra",
            designation: "JR Technical Officer",
            email: "2024.shivam.mishra@ves.ac.in",
            github: "https://github.com/Thetwobraincells",
            linkedin: "https://www.linkedin.com/in/shivam-mishra-vesit/",
            image: "/images/team2025/seMembers/ShivamMishra.png",
          },
          {
            name: "Shruti Awasthi",
            designation: "JR Content Officer",
            email: "2024.shruti.awasthi@ves.ac.in",
            github: "https://github.com/being4440",
            linkedin: "https://www.linkedin.com/in/shruti-awasthi-b6180835a/",
            image: "/images/team2025/seMembers/ShrutiAwasthi.png",
          },
          {
            name: "Soniya Lulla",
            designation: "JR Public Relations Officer",
            email: "2024.soniya.lulla@ves.ac.in",
            github: "https://github.com/lullasoniya4-dotcom",
            linkedin: "https://www.linkedin.com/in/soniya-lulla-36b072338/",
            image: "/images/team2025/seMembers/SoniyaLulla.png",
          },
          {
            name: "Sujal Gupta",
            designation: "JR Technical Officer",
            email: "2024.sujal.gupta@ves.ac.in",
            github: "https://github.com/acchasujal",
            linkedin: "https://www.linkedin.com/in/sujal-gupta-78a452326/",
            image: "/images/team2025/seMembers/SujalGupta.png",
          },
          {
            name: "Tanaya Pawar",
            designation: "JR Graphics Officer",
            email: "2024.tanaya.pawar@ves.ac.in",
            github: "https://github.com/Tana2006",
            linkedin: "https://www.linkedin.com/in/tanaya-pawar-7420aa379/",
            image: "/images/team2025/seMembers/TanayaPawar.png",
          },
          {
            name: "Unmesh Bhangale",
            designation: "JR Content Officer",
            email: "2024.unmesh.bhangale@ves.ac.in",
            github: "https://github.com/imunmesh",
            linkedin: "https://www.linkedin.com/in/unmesh-bhangale-992995343/",
            image: "/images/team2025/seMembers/UnmeshBhangale.png",
          },
        ],
      },
    ],
  },
  {
    value: "Quest IT Council 2024-25",
    title: "Quest IT Council 2024-25",
    subGroups: [
      {
        value: "BE Members",
        title: "BE Members",
    members: [
      {
        name: "Raghav Mundhara",
        designation: "Technical Head",
        email: "2021.raghav.mundhara@ves.ac.in",
        github: "https://github.com/Raghav-Mundhara",
        linkedin: "https://www.linkedin.com/in/raghav-mundhara",
        image:
          "https://res.cloudinary.com/bytewise0405/image/upload/v1736245319/QuestIT/Team/BE/raghav-mundhara_xvser5.jpg",
      },
      {
        name: "Vishal Gori",
        designation: "Technical Head",
        email: "2021.vishal.gori@ves.ac.in",
        github: "https://github.com/Vishal-Gori",
        linkedin: "https://in.linkedin.com/in/vishal-gori-710106214",
        image:
          "https://res.cloudinary.com/bytewise0405/image/upload/v1736258326/QuestIT/Team/BE/vishal-gori_cz7zew.jpg",
      },
      {
        name: "Anket Kadam ",
        designation: "Technical Head",
        email: "2021.anket.kadam@ves.ac.in",
        github: "https://github.com/Anket08042003",
        linkedin: "https://www.linkedin.com/in/anket-kadam-358b8a260",
        image:
          "https://res.cloudinary.com/bytewise0405/image/upload/v1736245320/QuestIT/Team/BE/anket-kadam_lj5i5d.png",
      },
      {
        name: "Siddhant Bhoi",
        designation: "Secretary",
        email: "d2021.siddhant.bhoi@ves.ac.in",
        github: "https://github.com/sidhhu0603",
        linkedin: "https://www.linkedin.com/in/siddhant-bhoi-3923671a6",
        image:
          "https://res.cloudinary.com/bytewise0405/image/upload/v1736258326/QuestIT/Team/BE/siddhant-bhoi_d0hrlu.jpg",
      },
      {
        name: "Ruchita Dalvi",
        designation: "Graphics Head",
        email: "d2021.ruchita.dalvi@ves.ac.in",
        github: "https://github.com/Ruchita-20",
        linkedin: "https://www.linkedin.com/in/ruchita-dalvi-a11ba7296",
        image:
          "https://res.cloudinary.com/bytewise0405/image/upload/v1736258325/QuestIT/Team/BE/ruchita-dalvi_fgnq4p.jpg",
      },
      {
        name: "Siddhi Bhogale",
        designation: "Technical Head",
        email: "bhogalesiddhi640@gmail.com",
        github: "https://github.com/bhogalesiddhi",
        linkedin: "https://in.linkedin.com/in/bhogalesiddhi",
        image:
          "https://res.cloudinary.com/bytewise0405/image/upload/v1736258326/QuestIT/Team/BE/siddhi-bhogale_ekvoig.jpg",
      },
      {
        name: "Soham Phalke",
        designation: "Content Head",
        email: "2021.soham.phalke@ves.ac.in",
        github: "https://github.com/stg2209",
        linkedin: "https://www.linkedin.com/in/soham-phalke-5084b0261",
        image:
          "https://res.cloudinary.com/bytewise0405/image/upload/v1736258326/QuestIT/Team/BE/soham-phalke_m7rgea.jpg",
      },
      {
        name: "Kanak Pendse",
        email: "kanak.pendse14@gmail.com",
        designation: "Public Relations Head",
        linkedin: "https://in.linkedin.com/in/kanak-pendse-832b5a251",
        image:
          "https://res.cloudinary.com/bytewise0405/image/upload/v1736258325/QuestIT/Team/BE/kanak-pendse_cwpy2z.jpg",
      },
      {
        name: "Nishtha Joshi",
        designation: "Secretary",
        email: "2021.nishtha.joshi@ves.ac.in",
        github: "https://github.com/joshinishtha99",
        linkedin: "https://www.linkedin.com/in/joshi-nishtha",
        image:
          "https://res.cloudinary.com/bytewise0405/image/upload/v1736258325/QuestIT/Team/BE/nishtha-joshi_rro3yo.jpg",
      },
      {
        name: "Soham Nimbalkar",
        designation: "Technical Head",
        github: "https://github.com/NimbalkarSoham",
        linkedin: "https://in.linkedin.com/in/soham-nimbalkar-58853a252",
        image:
          "https://res.cloudinary.com/bytewise0405/image/upload/v1738430274/QuestIT/Team/BE/soham-nimbalkar_pktlrt.jpg",
      },
    ],
      },
      {
        value: "TE Members",
        title: "TE Members",
    members: [
      {
        name: "Ronak Katariya",
        email: "2022.ronak.katariya@ves.ac.in",
        github: "https://github.com/ronak03rsk",
        designation: "SR Public Relations Officer",
        linkedin: "https://www.linkedin.com/in/ronak-katariya-02877b284",
        image:
          "https://res.cloudinary.com/bytewise0405/image/upload/v1736259227/QuestIT/Team/TE/ronak-katariya_nvukhj.png",
      },
      {
        name: "Pranav Titambe",
        designation: "SR Technical Officer",
        email: "2022.pranav.titambe@ves.ac.in",
        github: "https://github.com/Pranavlovescode",
        linkedin: "https://in.linkedin.com/in/pranav-titambe",
        image:
          "https://res.cloudinary.com/bytewise0405/image/upload/v1736244063/QuestIT/Team/TE/pranav-titambe_faqqqs.jpg",
      },
      {
        name: "Mohit Kerkar",
        designation: "SR Content Writer",
        email: "2022.mohit.kerkar@ves.ac.in",
        linkedin: "https://in.linkedin.com/in/mohit-kerkar-a196a9255",
        image:
          "https://res.cloudinary.com/bytewise0405/image/upload/v1736259227/QuestIT/Team/TE/mohit-kerkar_i9vpu5.jpg",
      },
      {
        name: "Aryan Dangat",
        designation: "SR Content Writer",
        email: "2022.aryan.dangat@ves.ac.in",
        github: "https://github.com/Aryan2052",
        linkedin: "https://www.linkedin.com/in/aryan-d-394450199",
        image:
          "https://res.cloudinary.com/bytewise0405/image/upload/v1736259228/QuestIT/Team/TE/aryan-dangat_dldwfv.jpg",
      },
      {
        name: "Dhruv Maurya",
        designation: "SR Graphics Officer",
        email: "2022.dhruv.maurya@ves.ac.in",
        github: "https://github.com/Dhruv07Maurya",
        image:
          "https://res.cloudinary.com/bytewise0405/image/upload/v1736244062/QuestIT/Team/TE/dhruv-maurya_dqgcsw.jpg",
      },
      {
        name: "Roma Shirodkar",
        designation: "Deputy Secretary",
        email: "2022.roma.shirodkar@ves.ac.in",
        github: "https://github.com/RomaShirodkar19",
        linkedin: "https://www.linkedin.com/in/roma-shirodkar-3817852b2",
        image:
          "https://res.cloudinary.com/bytewise0405/image/upload/v1736259227/QuestIT/Team/TE/roma-shirodkar_iohp46.jpg",
      },
      {
        name: "Eesha Chavan",
        designation: "Deputy Secretary",
        email: "2022.eesha.chavan@ves.ac.in",
        github: "https://github.com/eeshachavan",
        linkedin: "https://www.linkedin.com/in/eesha-chavan",
        image:
          "https://res.cloudinary.com/bytewise0405/image/upload/v1736259228/QuestIT/Team/TE/eesha-chavan_lsh67g.jpg",
      },
      {
        name: "Pratik Patil",
        designation: "SR Technical Officer",
        email: "2022.pratik.patil@ves.ac.in",
        github: "https://github.com/Pratik9113",
        linkedin: "https://www.linkedin.com/in/pratik-patil-b5681424b",
        image:
          "https://res.cloudinary.com/bytewise0405/image/upload/v1736245706/QuestIT/Team/TE/pratik-patil_jt1vpl.png",
      },
      {
        name: "Prajjwal Pandey",
        designation: "SR Technical Officer",
        email: "2022.prajjwal.pandey@ves.ac.in",
        github: "https://github.com/Prajjwal-pep",
        linkedin: "https://in.linkedin.com/in/prajjwal-pandey-a82b44264",
        image:
          "https://res.cloudinary.com/bytewise0405/image/upload/v1736263872/QuestIT/Team/TE/prajjwal-pandey_s66qyy.jpg",
      },
      {
        name: "Sannidhi Kailaje",
        designation: "SR Graphics Officer",
        github: "https://github.com/Skailaje",
        email: "2022.sannidhi.kailaje@ves.ac.in",
        linkedin: "https://www.linkedin.com/in/sannidhi-kailaje-011a312a4",
        image:
          "https://res.cloudinary.com/bytewise0405/image/upload/v1738430294/QuestIT/Team/TE/sannidhi-kailaje_pdurd0.jpg",
      },
    ],
      },
      {
        value: "SE Members",
        title: "SE Members",
    members: [
      {
        name: "Nupur Ghangarekar",
        designation: "JR Technical Officer",
        email: "2023.nupur.ghangarekar@ves.ac.in",
        github: "https://github.com/NupurGhangarekar",
        linkedin: "https://www.linkedin.com/in/nupur-ghangarekar-60291b291",
        image:
          "https://res.cloudinary.com/bytewise0405/image/upload/v1736258903/QuestIT/Team/SE/nupur-ghangarekar_uyebtz.jpg",
      },
      {
        name: "Ayush Karanth",
        email: "2023.ayush.karanth@ves.ac.in",
        github: "https://github.com/Ayushkaranth",
        designation: "JR Public Relations Officer",
        linkedin: "https://www.linkedin.com/in/ayush-karanth-7276922a4",
        image:
          "https://res.cloudinary.com/bytewise0405/image/upload/v1736258903/QuestIT/Team/SE/ayush-karanth_pxhd7n.jpg",
      },
      {
        name: "Monica Ahuja",
        designation: "JR Graphic Officer",
        email: "2023.monica.ahuja@ves.ac.in",
        github: "https://github.com/ahujamonica",
        linkedin: "https://www.linkedin.com/in/monica-ahuja01",
        image:
          "https://res.cloudinary.com/bytewise0405/image/upload/v1736258903/QuestIT/Team/SE/monica-ahuja_smy79q.jpg",
      },
      {
        name: "Arnav Chaudhary",
        designation: "JR Technical Officer",
        email: "2023.arnav.chaudhary@ves.ac.in",
        github: "https://github.com/Arnavch2024",
        linkedin: "https://www.linkedin.com/in/arnav-chaudhary-2a526928b",
        image:
          "https://res.cloudinary.com/bytewise0405/image/upload/v1736258903/QuestIT/Team/SE/arnav-chaudhary_kmysjh.jpg",
      },
      {
        name: "Vaishnavi Avhad",
        email: "2023.vaishnavi.avhad@ves.ac.in",
        github: "https://github.com/Vaishnavii-01",
        designation: "JR Public Relations Officer",
        linkedin: "https://www.linkedin.com/in/vaishnavi-avhad-056969330",
        image:
          "https://res.cloudinary.com/bytewise0405/image/upload/v1738430324/QuestIT/Team/SE/vaishnavi-avhad_nwu1ac.jpg",
      },
      {
        name: "Jay Kerkar",
        designation: "JR Technical Officer",
        email: "2023.jay.kerkar@ves.ac.in",
        github: "https://github.com/jaykerkar0405",
        linkedin: "https://www.linkedin.com/in/jaykerkar0405",
        image:
          "https://res.cloudinary.com/bytewise0405/image/upload/v1736243132/QuestIT/Team/SE/jay-kerkar_ksqatl.png",
      },
      {
        name: "Harshita Singh",
        email: "2023.harshita.singh@ves.ac.in",
        github: "https://github.com/HarshitaS01",
        designation: "JR Public Relations Officer",
        linkedin: "https://www.linkedin.com/in/harshita-singh-3846302a4",
        image:
          "https://res.cloudinary.com/bytewise0405/image/upload/v1736258903/QuestIT/Team/SE/harshita-singh_sxutyq.jpg",
      },
      {
        name: "Nidhi Puthran",
        designation: "JR Graphics Officer",
        email: "2023.nidhi.puthran@ves.ac.in",
        github: "https://github.com/nidhi0810",
        linkedin: "https://www.linkedin.com/in/nidhi-puthran-2824a9299",
        image:
          "https://res.cloudinary.com/bytewise0405/image/upload/v1736258902/QuestIT/Team/SE/nidhi-puthran_qdbo8i.jpg",
      },
      {
        name: "Anushka Sharma",
        designation: "JR Graphics Officer",
        email: "2023.anushka.sharma@ves.ac.in",
        github: "https://github.com/Anu-shhkaa",
        linkedin: "https://www.linkedin.com/in/anushka-sharma-0543832a1",
        image:
          "https://res.cloudinary.com/bytewise0405/image/upload/v1736258902/QuestIT/Team/SE/anushka-sharma_iozkpv.jpg",
      },
      {
        name: "Sameeksha Sankpal",
        designation: "JR Technical Officer",
        github: "https://github.com/sameeksha15",
        email: "2023.sameeksha.sankpal@ves.ac.in",
        linkedin: "https://www.linkedin.com/in/sameeksha-sankpal-12aa72251",
        image:
          "https://res.cloudinary.com/bytewise0405/image/upload/v1736243127/QuestIT/Team/SE/sameeksha-sankpal_ljptpu.jpg",
      },
      {
        name: "Varun Rahatgaonkar",
        designation: "JR Social Media Manager",
        email: "2023.varun.rahatgaonkar@ves.ac.in",
        github: "https://github.com/kingslaye-varun",
        linkedin: "https://www.linkedin.com/in/varun-rahatgaonkar-448392321",
        image:
          "https://res.cloudinary.com/bytewise0405/image/upload/v1736258902/QuestIT/Team/SE/varun-rahatgaonkar_kozoi5.jpg",
      },
      {
        name: "Archit Chitte",
        designation: "JR Graphics Officer",
        email: "2023.archit.chitte@ves.ac.in",
        github: "https://github.com/architchitte",
        linkedin: "https://in.linkedin.com/in/archit-chitte-4551ba288",
        image:
          "https://res.cloudinary.com/bytewise0405/image/upload/v1736258902/QuestIT/Team/SE/archit-chitte_g8h6ti.jpg",
      },
      {
        name: "Shravanya Andhale",
        designation: "JR Technical Officer",
        email: "2023.shravanya.andhale@ves.ac.in",
        github: "https://github.com/Shravanya178",
        linkedin: "https://www.linkedin.com/in/shravanya-andhale-b729a2314",
        image:
          "https://res.cloudinary.com/bytewise0405/image/upload/v1736243128/QuestIT/Team/SE/shravanya-andhale_usemz5.jpg",
      },
      {
        name: "Harsh Kumar",
        email: "2023.harsh.kumar@ves.ac.in",
        designation: "JR Social Media Manager",
        image:
          "https://res.cloudinary.com/bytewise0405/image/upload/v1736258902/QuestIT/Team/SE/harsh-kumar_m3u0oy.jpg",
      },
      {
        name: "Anish Tawade",
        designation: "JR Graphics Officer",
        email: "2023.anish.tawade@ves.ac.in",
        github: "https://github.com/Anissh280507",
        linkedin: "https://in.linkedin.com/in/anish-tawade-53a82a1ba",
        image:
          "https://res.cloudinary.com/bytewise0405/image/upload/v1736242752/QuestIT/Team/SE/anish-tawade_ejnuxi.jpg",
      },
    ],
      },
    ],
  },
];

export default team;
